### PR TITLE
Move taps and sqlite gems to development group.

### PR DESCRIPTION
**Pull request by derwiki**
`sqlite` not being scoped to development is causing an error when I push to Heroku.

### CODE REVIEW

**Comment by nuprin** [comment]
Howdy. I'd like for Lann to review / merge. The change seems pretty
innocuous, I just want to make sure it doesn't break our current production
environment.

On Tue, May 21, 2013 at 3:08 PM, Adam Derewecki notifications@github.comwrote:

> sqlite not being scoped to development is causing an error when I push to
> 
> ## Heroku.
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/apartmentlist/stars-causes master
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/causes/stars-causes/pull/2
> Commit Summary
> - Move taps and sqlite to development group in Gemfile
> 
> File Changes
> - _M_ Gemfilehttps://github.com/causes/stars-causes/pull/2/files#diff-0(4)
> 
> Patch Links:
> - https://github.com/causes/stars-causes/pull/2.patch
> - https://github.com/causes/stars-causes/pull/2.diff

## 

Chris Chan
VP of Product, Causes
http://causes.com

**Comment by ascandella** [comment]
I reviewed and tested this locally, I'm giving this my "it's not a trojan horse" seal of approval.

https://gerrit.causes.com/#/q/status:open+project:stars-causes,n,z

**Comment by nuprin** [comment]
Sounds good.

On Tue, May 21, 2013 at 3:28 PM, Aiden Scandella
notifications@github.comwrote:

> I reviewed and tested this locally, I'm giving this my "it's not a trojan
> horse" seal of approval.
> 
> https://gerrit.causes.com/#/q/status:open+project:stars-causes,n,z
> 
> On Tuesday, May 21, 2013 at 3:12 PM, Chris Chan wrote:
> 
> > Howdy. I'd like for Lann to review / merge. The change seems pretty
> > innocuous, I just want to make sure it doesn't break our current
> > production
> > environment.
> > 
> > On Tue, May 21, 2013 at 3:08 PM, Adam Derewecki <
> > notifications@github.com (mailto:notifications@github.com)>wrote:
> > 
> > > sqlite not being scoped to development is causing an error when I push
> > > to
> > > 
> > > ## Heroku.
> > > 
> > > You can merge this Pull Request by running
> > > 
> > > git pull https://github.com/apartmentlist/stars-causes master
> > > 
> > > Or view, comment on, or merge it at:
> > > 
> > > https://github.com/causes/stars-causes/pull/2
> > > Commit Summary
> > > - Move taps and sqlite to development group in Gemfile
> > > 
> > > File Changes
> > > - _M_ Gemfile<
> > >   https://github.com/causes/stars-causes/pull/2/files#diff-0>(4)
> > > 
> > > Patch Links:
> > > - https://github.com/causes/stars-causes/pull/2.patch
> > > - https://github.com/causes/stars-causes/pull/2.diff
> > 
> > ## 
> > 
> > Chris Chan
> > VP of Product, Causes
> > http://causes.com
> > 
> > —
> > Reply to this email directly or view it on GitHub (
> > https://github.com/causes/stars-causes/pull/2#issuecomment-18245303).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/causes/stars-causes/pull/2#issuecomment-18246022
> .

## 

Chris Chan
VP of Product, Causes
http://causes.com

**Comment by ascandella** [comment]
Cherry-picked at bfe6606. Thanks, Adam!

**Pull request closed without merging**
